### ISSUE TITLE
RFE: Code Coverage

### ISSUE THREAD

**Issue by gundalow** [ansible/dci-partner-ansible#20]

**Comment by Spredzy** [comment]
@gundalow Could you give more details in this issue, in order to know what we're talking about. I know coverage, but in what way? What do you want to achieve? What are the goals/wishes?

**Comment by gundalow** [comment]
This is something I'll look at, the aim is to get the DCI coverage results added into https://codecov.io/gh/ansible/ansible/

There are some uncomitted changed in `hooks` that use `ansible-test` to generate the coverage data. The next step will be to process the results and upload them to `codecov.io`

**Comment by gundalow** [comment]
We are using Projects in the main `ansible/ansible` project now, so moving this to https://github.com/ansible/ansible/issues/31197
